# Generated by Django 5.1.6 on 2025-02-27 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konfirensiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='yangilik_images')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('boshlanish_sanasi', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('body_small', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Konfirensiya',
                'verbose_name_plural': 'Konfirensiyalar',
                'ordering': ['boshlanish_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='rahbariyat_images/')),
                ('lavozimi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numbers', models.IntegerField()),
                ('bio', models.TextField(default='')),
                ('telegram', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Tadbir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='yangilik_images')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('boshlanish_sanasi', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('body_small', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['boshlanish_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='Tanlov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='yangilik_images')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('boshlanish_sanasi', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('body_small', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tanlov',
                'verbose_name_plural': 'Tanlovlar',
                'ordering': ['boshlanish_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='Togaraklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='nomi')),
                ('image', models.ImageField(upload_to='togarak_images')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(verbose_name="To'garak haqida ba'tafsil")),
                ('body_small', models.CharField(max_length=250, verbose_name="To'garak haqida qisqacha")),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "To'garak",
                'verbose_name_plural': "To'garaklar",
                'ordering': ['-publish_time'],
            },
        ),
    ]
