# Generated by Django 5.1.6 on 2025-02-27 18:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0002_remove_togaraklar_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('body_small', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('narxi', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Budjet',
                'verbose_name_plural': 'Budjetlar',
                'ordering': ['publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Oxirgi_ishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('body_small', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='oxirgi_images/')),
                ('publish_time', models.DateField(default=datetime.datetime(2025, 2, 27, 18, 6, 49, 723599, tzinfo=datetime.timezone.utc), verbose_name='Oxirgi qilingan ish sanasi ')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Budjet',
                'verbose_name_plural': 'Budjetlar',
                'ordering': ['publish_time'],
            },
        ),
    ]
