# Generated by Django 5.1.6 on 2025-02-27 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0003_budjet_oxirgi_ishlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budjet',
            options={'ordering': ['-publish_time'], 'verbose_name': 'Budjet', 'verbose_name_plural': 'Budjetlar'},
        ),
        migrations.AlterModelOptions(
            name='rahbariyat',
            options={'ordering': ['-publish_time'], 'verbose_name_plural': 'Rahbariyat'},
        ),
        migrations.AlterField(
            model_name='oxirgi_ishlar',
            name='publish_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Oxirgi qilingan ish sanasi '),
        ),
    ]
