# Generated by Django 5.1.6 on 2025-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0004_alter_budjet_options_alter_rahbariyat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maktablar', models.PositiveIntegerField(default=0)),
                ('bogchalar', models.PositiveIntegerField(default=0)),
                ('yangilanishlar', models.PositiveIntegerField(default=0)),
                ('rejada', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Maktab,bogcha soni',
                'verbose_name_plural': 'Maktab,bogchalar soni',
            },
        ),
        migrations.AlterModelOptions(
            name='oxirgi_ishlar',
            options={'ordering': ['publish_time'], 'verbose_name': 'Oxirgi ish', 'verbose_name_plural': 'Oxirgi ishlar'},
        ),
    ]
