# Generated by Django 5.1.6 on 2025-02-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0005_numbers_alter_oxirgi_ishlar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hududiy_Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='rahbariyat_images/')),
                ('lavozimi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numbers', models.IntegerField()),
                ('bio', models.TextField(default='')),
                ('telegram', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['-publish_time'],
            },
        ),
    ]
