# Generated by Django 5.1.6 on 2025-02-28 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0006_hududiy_rahbariyat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korrupsiya_kurash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('body_small', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='korrupsiya_images/')),
                ('publish_time', models.DateField(default=django.utils.timezone.now, verbose_name=" Targ'ibot sanasi ")),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Korrupsiyaga qarshi kurash',
                'ordering': ['publish_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='hududiy_rahbariyat',
            options={'ordering': ['-publish_time'], 'verbose_name_plural': "Hududiy Bo'lim Rahbarlari"},
        ),
        migrations.AlterField(
            model_name='konfirensiya',
            name='image',
            field=models.ImageField(upload_to='konfirensiya_images/'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='yangilanishlar',
            field=models.PositiveIntegerField(default=0, verbose_name="Qayta ta'mirlanganlar soni"),
        ),
        migrations.AlterField(
            model_name='tadbir',
            name='image',
            field=models.ImageField(upload_to='tadbir_images/'),
        ),
        migrations.AlterField(
            model_name='tanlov',
            name='image',
            field=models.ImageField(upload_to='tanlov_images/'),
        ),
        migrations.AlterField(
            model_name='togaraklar',
            name='image',
            field=models.ImageField(upload_to='togarak_images/'),
        ),
    ]
