# Generated by Django 5.1.6 on 2025-03-01 18:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0007_korrupsiya_kurash_alter_hududiy_rahbariyat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ')),
            ],
        ),
    ]
