# Generated by Django 5.1.6 on 2025-03-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bayonotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='rahbariyat_images/')),
                ('lavozimi', models.CharField(max_length=100)),
                ('body', models.TextField(default='')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bayonotlar',
                'ordering': ['-publish_time'],
            },
        ),
    ]
