# Generated by Django 5.1.6 on 2025-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0009_bayonotlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harakatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maktablar', models.PositiveIntegerField(default=0)),
                ('bogchalar', models.PositiveIntegerField(default=0)),
                ('yangilanishlar', models.PositiveIntegerField(default=0, verbose_name="Qayta ta'mirlanganlar soni")),
                ('rejada', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Harakatlar strategiyasi',
                'verbose_name_plural': 'Harakatlar strategiyasi raqamlari',
            },
        ),
    ]
