# Generated by Django 5.1.6 on 2025-03-02 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0010_harakatlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar turi',
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField()),
                ('body_small', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='yangiliklar_images/')),
                ('active', models.BooleanField(default=True)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.yangiliklar_turi')),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-date'],
            },
        ),
    ]
