# Generated by Django 5.1.6 on 2025-03-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0011_yangiliklar_turi_yangiliklar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': "Bog'lanishlar"},
        ),
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'ordering': ['date'], 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AddField(
            model_name='yangiliklar_turi',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
