# Generated by Django 5.1.6 on 2025-03-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0012_alter_contact_options_alter_yangiliklar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konfirensiya',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-12 14:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yangiliklar',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-12 10:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yangiliklar_turi',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
