# Generated by Django 5.1.6 on 2025-03-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0014_alter_konfirensiya_options_alter_yangiliklar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasmlar_turlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='tadbir',
            options={'ordering': ['-boshlanish_sanasi'], 'verbose_name': 'Tadbir', 'verbose_name_plural': 'Tadbirlar'},
        ),
        migrations.AlterModelOptions(
            name='tanlov',
            options={'ordering': ['-boshlanish_sanasi'], 'verbose_name': 'Tanlov', 'verbose_name_plural': 'Tanlovlar'},
        ),
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery_rasmlar/')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.rasmlar_turlari')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'ordering': ['-publish_time'],
            },
        ),
    ]
