# Generated by Django 5.1.6 on 2025-03-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0015_rasmlar_turlari_alter_tadbir_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasmlar_turlari',
            options={'ordering': ['-publish_time'], 'verbose_name': 'Rasmlar_turlari', 'verbose_name_plural': 'Rasmlar_turlari'},
        ),
        migrations.AddField(
            model_name='rasmlar_turlari',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
