# Generated by Django 5.1.6 on 2025-03-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0016_alter_rasmlar_turlari_options_rasmlar_turlari_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasmlar',
            name='turi',
        ),
        migrations.DeleteModel(
            name='Rasmlar_turlari',
        ),
    ]
