# Generated by Django 5.1.6 on 2025-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0017_remove_rasmlar_turi_delete_rasmlar_turlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasmlar_turlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rasmlar_turlari',
                'verbose_name_plural': 'Rasmlar_turlari',
                'ordering': ['-publish_time'],
            },
        ),
    ]
